"""Seed the corpus with the foundational *Code Biology* texts as **code 0**.

This is the code-0 analogue of the extract_csv (step 1) + download_pdfs (step 2)
ingestion: rather than parsing the source PDF and downloading from a DOI, it takes
a hand-curated manifest of seminal Code Biology papers (Barbieri's and Major's
defining texts), copies their PDFs into ``pdfs/`` under the **same** naming
convention the downloader uses (``download_pdfs.output_path_for``), and appends a
row per paper to ``biological_codes.csv`` under the reserved ``Code Number 0`` /
``Code Name "Code Biology"``.

Why a reserved code 0: these papers don't belong to any of Barbieri's 435 numbered
codes — they *define* the criteria the codes are measured against (CLAUDE.md §1).
Holding them under code 0 makes them first-class corpus members (they flow through
embedding, topic assignment and the judge like any other paper) while staying
trivially separable, and leaves room to add more foundational papers later by
appending manifest rows.

Idempotent and re-runnable: ``extract_csv`` regenerates ``biological_codes.csv``
from scratch (codes 1-435), wiping appended rows, so this step is designed to run
**after** extraction and re-append only what's missing — re-running never
duplicates a CSV row or re-copies a PDF already on disk. Pure logic (manifest
parse, naming, row building, append planning) is unit-tested; the copy is a plain
``shutil.copy2``.

Pipeline position (CLAUDE.md §2): runs after step 1 (extract_csv), before step 2
(download_pdfs) — the foundational PDFs are placed directly, not downloaded.

    python3 seed_code_biology.py            # uses code_biology_seed.csv
"""

import argparse
import csv
import logging
import os
import shutil

import download_pdfs

logger = logging.getLogger(__name__)

MANIFEST = "code_biology_seed.csv"   # columns: Source File, Paper Name, URL
SOURCE_DIR = "Code_Biology_PDFs"     # where the curated PDFs live
CODES_CSV = "biological_codes.csv"
CODE_NUMBER = "0"
CODE_NAME = "Code Biology"


# --- manifest --------------------------------------------------------------

def load_manifest(path=MANIFEST):
    """Parse the seed manifest into ``[{source_file, paper_name, url}, ...]``.

    ``URL`` is optional — a book without a DOI just carries an empty URL and is
    named from its source filename instead (see :func:`dest_path_for`)."""
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            rows.append({
                "source_file": row["Source File"].strip(),
                "paper_name": row["Paper Name"].strip(),
                "url": (row.get("URL") or "").strip(),
            })
    return rows


# --- corpus-consistent naming ----------------------------------------------

def dest_path_for(entry, output_dir=download_pdfs.OUTPUT_DIR):
    """Destination ``pdfs/`` path for a manifest entry.

    With a URL, reuse :func:`download_pdfs.output_path_for` so the file is named
    exactly as the downloader would have named it (DOI-named when the URL carries a
    DOI) — keeping ``pdf_path`` identical to the rest of the corpus. Without a URL
    (a book with no DOI), slug the source filename's stem (no doubled ``.pdf``)."""
    if entry.get("url"):
        return download_pdfs.output_path_for({"url": entry["url"]}, output_dir)
    stem = os.path.splitext(os.path.basename(entry["source_file"]))[0]
    return os.path.join(output_dir, f"{download_pdfs.url_slug(stem)}.pdf")


def code_row(entry):
    """Build the ``biological_codes.csv`` row for a manifest entry (code 0)."""
    return [CODE_NUMBER, CODE_NAME, entry["paper_name"], entry["url"]]


# --- idempotent append planning --------------------------------------------

def _present_keys(existing_rows):
    """The URL (preferred) or paper-name keys of code-0 rows already in the CSV."""
    keys = set()
    for r in existing_rows:
        if str(r.get("Code Number", "")).strip() != CODE_NUMBER:
            continue
        url = (r.get("URL") or "").strip()
        keys.add(url or (r.get("Paper Name") or "").strip())
    return keys


def rows_to_append(manifest, existing_rows):
    """Code-0 rows from ``manifest`` not already present in ``existing_rows``.

    A manifest entry is 'already seeded' if a code-0 row shares its URL (when it has
    one) or its paper name (when it doesn't) — so the step is idempotent against a
    CSV that was just regenerated by extract_csv and re-seeded."""
    present = _present_keys(existing_rows)
    out = []
    for entry in manifest:
        key = entry["url"] or entry["paper_name"]
        if key in present:
            continue
        present.add(key)  # guard against duplicate manifest rows in one pass
        out.append(code_row(entry))
    return out


# --- orchestration ---------------------------------------------------------

def append_rows(codes_csv, rows):
    """Append already-built rows to the codes CSV (created with a header if absent)."""
    new_file = not os.path.exists(codes_csv)
    with open(codes_csv, "a", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        if new_file:
            w.writerow(["Code Number", "Code Name", "Paper Name", "URL"])
        w.writerows(rows)


def seed(manifest_path=MANIFEST, codes_csv=CODES_CSV,
         source_dir=SOURCE_DIR, output_dir=download_pdfs.OUTPUT_DIR):
    """Copy missing foundational PDFs into ``output_dir`` and append missing code-0
    rows to ``codes_csv``. Returns the number of CSV rows appended.

    Copy and CSV append are independent idempotent operations: a PDF already on disk
    is left untouched, a code-0 row already present is not re-added — so a corpus
    that already has the files but a freshly-regenerated CSV is repaired correctly."""
    manifest = load_manifest(manifest_path)
    os.makedirs(output_dir, exist_ok=True)

    for entry in manifest:
        src = os.path.join(source_dir, entry["source_file"])
        dest = dest_path_for(entry, output_dir)
        if os.path.exists(dest):
            continue
        if not os.path.exists(src):
            logger.warning("manifest source missing, skipping copy: %s", src)
            continue
        shutil.copy2(src, dest)
        logger.info("copied %s -> %s", entry["source_file"], dest)

    existing = []
    if os.path.exists(codes_csv):
        with open(codes_csv, newline="", encoding="utf-8") as f:
            existing = list(csv.DictReader(f))
    rows = rows_to_append(manifest, existing)
    if rows:
        append_rows(codes_csv, rows)
    logger.info("appended %d code-0 row(s) to %s", len(rows), codes_csv)
    return len(rows)


def main():
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s [%(name)s] %(message)s")
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest", default=MANIFEST)
    ap.add_argument("--codes-csv", default=CODES_CSV)
    ap.add_argument("--source-dir", default=SOURCE_DIR)
    ap.add_argument("--output-dir", default=download_pdfs.OUTPUT_DIR)
    args = ap.parse_args()
    seed(args.manifest, args.codes_csv, args.source_dir, args.output_dir)


if __name__ == "__main__":
    main()
